(function () {
  const TEAM_INFO = {
    name: "BiSKY Team",
    motto: "[LEMA OFICIAL BISKY TEAM]",
    campus: "Universidad del Pais Vasco / Euskal Herriko Unibertsitatea",
    focus: "Desarrollo aeroespacial universitario orientado a cohetes, motores y sistemas de lanzamiento",
  };

  const YEARS = [2025, 2024, 2023];

  const DEPARTMENT_ORDER = [
    "Leadership",
    "Propulsion",
    "Structures",
    "Avionics",
    "Recovery",
    "Operations",
    "Faculties",
  ];

  const POSITION_ORDER = [
    "Team Leader",
    "Financial Manager",
    "Project Manager",
    "Chief",
    "Technical",
    "Member",
    "Faculty Advisor",
  ];

  const MEMBERS = [
    {
      id: "aina-salazar",
      name: "Aina Salazar",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Team Leader",
      tagline: "Coordinacion integral de roadmap, operaciones de vuelo y gestion interdepartamental.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "ResearchGate", url: "https://www.researchgate.net/" }],
      participation: [
        { year: 2025, department: "Leadership", position: "Team Leader", title: "Team Leader" },
        { year: 2024, department: "Operations", position: "Project Manager", title: "Project Manager" },
        { year: 2023, department: "Operations", position: "Technical", title: "Flight Operations" },
      ],
      summary: "Coordina la estrategia tecnica global del equipo y asegura la integracion entre propulsion, estructuras y avionica.",
      highlights: ["Plan de validacion de 14 hitos", "Gobernanza tecnica multiplataforma", "Interfaz con sponsors clave"],
    },
    {
      id: "iker-mendia",
      name: "Iker Mendia",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Financial Manager",
      tagline: "Planificacion financiera y estructura de adquisiciones para sistemas de alto rendimiento.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Portfolio", url: "#" }],
      participation: [
        { year: 2025, department: "Leadership", position: "Financial Manager", title: "Financial Manager" },
        { year: 2024, department: "Operations", position: "Project Manager", title: "Budget Operations" },
      ],
      summary: "Orquesta presupuesto anual, compras tecnicas y acuerdos con proveedores de componentes criticos.",
      highlights: ["Optimizo costes de ensayos un 22%", "Pipeline de procurement tecnico", "Control de riesgo financiero"],
    },
    {
      id: "june-arrieta",
      name: "June Arrieta",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Project Manager",
      tagline: "Planificacion de proyectos de lanzamiento y sincronizacion de milestones.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Missions Board", url: "#" }],
      participation: [
        { year: 2025, department: "Leadership", position: "Project Manager", title: "Project Manager" },
        { year: 2024, department: "Leadership", position: "Project Manager", title: "Systems Integration" },
      ],
      summary: "Conecta el avance tecnico de cada familia de proyectos con el calendario de pruebas y lanzamientos.",
      highlights: ["Cadencia quincenal de revisiones", "Gestor de dependencias interproyecto", "Metricas de madurez tecnica"],
    },
    {
      id: "unai-echevarria",
      name: "Unai Echevarria",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Chief Propulsion",
      tagline: "Direccion tecnica de motores solidos y arquitectura de combustion.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Lab Notes", url: "#" }],
      participation: [
        { year: 2025, department: "Propulsion", position: "Chief", title: "Chief Propulsion" },
        { year: 2024, department: "Propulsion", position: "Technical", title: "Motor Architecture" },
        { year: 2023, department: "Propulsion", position: "Member", title: "Combustion Member" },
      ],
      summary: "Lidera el diseno de camaras, toberas y protocolos de ensayo en banco para motores de la familia Ignis.",
      highlights: ["3 iteraciones de grano validadas", "Instrumentacion de alta frecuencia", "Diseno termico de tobera"],
    },
    {
      id: "leire-campos",
      name: "Leire Campos",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Propulsion Technical",
      tagline: "Ensayo, telemetria de banco y analisis de curvas de empuje.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Technical Notes", url: "#" }],
      participation: [
        { year: 2025, department: "Propulsion", position: "Technical", title: "Propulsion Technical" },
        { year: 2024, department: "Propulsion", position: "Member", title: "Propellant Team" },
      ],
      summary: "Modela desempeno de motores y define criterios de aceptacion para test estaticos.",
      highlights: ["Banco de pruebas automatizado", "Procesado de datos en tiempo real", "Protocolos de seguridad"],
    },
    {
      id: "marcelo-vega",
      name: "Marcelo Vega",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Propulsion Member",
      tagline: "Fabricacion de geometria de grano y soporte de ensayos.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "CV", url: "#" }],
      participation: [
        { year: 2025, department: "Propulsion", position: "Member", title: "Propulsion Member" },
        { year: 2024, department: "Propulsion", position: "Member", title: "Motor Fabrication" },
      ],
      summary: "Da soporte a integracion mecanica de motor y operaciones de test en laboratorio.",
      highlights: ["Fixtures de manufactura", "Control dimensional", "Soporte en montaje de ignitores"],
    },
    {
      id: "nora-ibarra",
      name: "Nora Ibarra",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Chief Structures",
      tagline: "Arquitectura estructural del fuselaje y cargas de vuelo.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Solid Models", url: "#" }],
      participation: [
        { year: 2025, department: "Structures", position: "Chief", title: "Chief Structures" },
        { year: 2024, department: "Structures", position: "Technical", title: "Airframe Design" },
        { year: 2023, department: "Structures", position: "Member", title: "Composites Member" },
      ],
      summary: "Define configuraciones de airframe, union estructural y margenes frente a carga axial y lateral.",
      highlights: ["Airframe modular R-series", "Analisis FEA de seccion critica", "Diseno para mantenibilidad"],
    },
    {
      id: "eneko-otero",
      name: "Eneko Otero",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Structures Technical",
      tagline: "Composites, uniones mecanicas y validacion de materiales.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Material Sheets", url: "#" }],
      participation: [
        { year: 2025, department: "Structures", position: "Technical", title: "Structures Technical" },
        { year: 2024, department: "Structures", position: "Member", title: "Composite Fabrication" },
      ],
      summary: "Trabaja en laminados, fixtures y procedimientos de control de calidad para secciones estructurales.",
      highlights: ["Matriz de cupones de traccion", "Union bulkhead optimizada", "Estandares de montaje"],
    },
    {
      id: "paula-ruiz",
      name: "Paula Ruiz",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Structures Member",
      tagline: "Montaje y soporte de integracion de airframe.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Profile", url: "#" }],
      participation: [
        { year: 2025, department: "Structures", position: "Member", title: "Structures Member" },
        { year: 2024, department: "Structures", position: "Member", title: "Mechanical Assembly" },
      ],
      summary: "Participa en procesos de manufactura y preparacion de secciones para integracion final.",
      highlights: ["Calibracion de tooling", "Trazabilidad de piezas", "Control de tolerancias"],
    },
    {
      id: "adrian-soto",
      name: "Adrian Soto",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Chief Avionics",
      tagline: "Arquitectura electronica, telemetria y software de vuelo.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Git Board", url: "#" }],
      participation: [
        { year: 2025, department: "Avionics", position: "Chief", title: "Chief Avionics" },
        { year: 2024, department: "Avionics", position: "Technical", title: "Flight Software" },
        { year: 2023, department: "Avionics", position: "Member", title: "Electronics Member" },
      ],
      summary: "Lidera stack de avionica embarcada, canal de telemetria y fiabilidad de adquisicion de datos.",
      highlights: ["Board revision B completada", "Canal redundante de telemetria", "Test rig hardware-in-the-loop"],
    },
    {
      id: "amaia-lorenzo",
      name: "Amaia Lorenzo",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Avionics Technical",
      tagline: "Desarrollo de sensorizacion y pipeline de datos de vuelo.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Datasets", url: "#" }],
      participation: [
        { year: 2025, department: "Avionics", position: "Technical", title: "Avionics Technical" },
        { year: 2024, department: "Avionics", position: "Member", title: "Sensor Systems" },
      ],
      summary: "Se centra en captura de datos inerciales, sincronizacion temporal y postproceso de telemetria.",
      highlights: ["Filtro inercial refinado", "Pipeline de validacion automatica", "Calibracion en banco"],
    },
    {
      id: "gorka-lafuente",
      name: "Gorka Lafuente",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Chief Recovery",
      tagline: "Diseno de recuperacion, secuencias de despliegue y seguridad.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Flight Safety", url: "#" }],
      participation: [
        { year: 2025, department: "Recovery", position: "Chief", title: "Chief Recovery" },
        { year: 2024, department: "Recovery", position: "Technical", title: "Recovery Systems" },
      ],
      summary: "Desarrolla arquitectura de paracaidas, compartimentos de eyeccion y validacion de despliegue.",
      highlights: ["Ensayos de despliegue escalados", "Redundancia de eyeccion", "Checklist de operacion"],
    },
    {
      id: "nahia-villar",
      name: "Nahia Villar",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Recovery Member",
      tagline: "Preparacion de sistemas de recuperacion y soporte en operaciones de campo.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Field Ops", url: "#" }],
      participation: [
        { year: 2025, department: "Recovery", position: "Member", title: "Recovery Member" },
        { year: 2024, department: "Recovery", position: "Member", title: "Recovery Operations" },
      ],
      summary: "Participa en integracion de canopy, empaquetado y validacion pre-vuelo.",
      highlights: ["Protocolos de inspeccion", "Entrenamiento de despliegue", "Preparacion de campo"],
    },
    {
      id: "sergio-prada",
      name: "Sergio Prada",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Chief Operations",
      tagline: "Plan operativo de lanzamientos y logistica tecnica del equipo.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Ops Dashboard", url: "#" }],
      participation: [
        { year: 2025, department: "Operations", position: "Chief", title: "Chief Operations" },
        { year: 2024, department: "Operations", position: "Technical", title: "Launch Coordination" },
        { year: 2023, department: "Operations", position: "Member", title: "Ground Operations" },
      ],
      summary: "Coordina seguridad en campo, tiempos de mission control y secuencia operativa de lanzamiento.",
      highlights: ["Simulacros completos de lanzamiento", "Procedimientos de contingencia", "Integracion de equipos"],
    },
    {
      id: "claudia-fuentes",
      name: "Claudia Fuentes",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Operations Member",
      tagline: "Soporte en operaciones de campo y documentacion tecnica.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Ops Notes", url: "#" }],
      participation: [
        { year: 2025, department: "Operations", position: "Member", title: "Operations Member" },
        { year: 2024, department: "Operations", position: "Member", title: "Ground Support" },
      ],
      summary: "Apoya configuracion de campo y trazabilidad de checklists operativos antes de cada ventana.",
      highlights: ["Control documental", "Checklist digital", "Soporte multi-equipo"],
    },
    {
      id: "mikel-astigarraga",
      name: "Mikel Astigarraga",
      image: "../assets/images/member-placeholder.svg",
      headlineRole: "Faculty Advisor",
      tagline: "Mentoria academica y supervision de rigor ingenieril.",
      linkedin: "https://www.linkedin.com/",
      links: [{ label: "Academic Profile", url: "#" }],
      participation: [
        { year: 2025, department: "Faculties", position: "Faculty Advisor", title: "Faculty Advisor" },
        { year: 2024, department: "Faculties", position: "Faculty Advisor", title: "Faculty Advisor" },
        { year: 2023, department: "Faculties", position: "Faculty Advisor", title: "Faculty Advisor" },
      ],
      summary: "Acompana al equipo en metodologia de ingenieria, validacion de diseno y documentacion tecnica.",
      highlights: ["Revision de arquitectura", "Estandar de seguridad", "Alineacion academica"],
    },
  ];

  const PROJECT_FAMILIES = {
    cohetes: {
      key: "cohetes",
      label: "Cohetes",
      description: "Vehiculos de vuelo y arquitecturas de airframe orientadas a campanas de lanzamiento universitario.",
      image: "../assets/images/project-rocket.svg",
    },
    motores: {
      key: "motores",
      label: "Motores",
      description: "Programas de propulsion solida, banco de ensayos y evolucion de rendimiento.",
      image: "../assets/images/project-motor.svg",
    },
    "launch-rails": {
      key: "launch-rails",
      label: "Launch Rails",
      description: "Sistemas de guiado y lanzamiento para operaciones de vuelo seguras y repetibles.",
      image: "../assets/images/project-rail.svg",
    },
    auxiliary: {
      key: "auxiliary",
      label: "Proyectos Auxiliares",
      description: "Desarrollos de soporte tecnico: telemetria, bancos y herramientas de integracion.",
      image: "../assets/images/project-aux.svg",
    },
  };

  const PROJECTS = [
    {
      id: "skylance-r1",
      name: "Skylance R1",
      family: "cohetes",
      year: 2025,
      status: "Integration",
      summary: "Cohete suborbital de demostracion tecnica con foco en estabilidad de vuelo y recuperacion redundante.",
      description:
        "Plataforma principal de vuelo de la temporada 2025. Integra nueva arquitectura estructural modular, avionica de revision B y sistema de recuperacion dual.",
      image: "../assets/images/project-rocket.svg",
      highlight: "Vehiculo flagship de la campana 2025.",
      specs: [
        { label: "Altura", value: "3.05 m" },
        { label: "Diametro", value: "160 mm" },
        { label: "Masa al despegue", value: "19.4 kg" },
        { label: "Altitud objetivo", value: "4.8 km AGL" },
      ],
      related: ["ignis-m1", "vector-rail-x", "recovery-suite"],
      gallery: ["../assets/images/project-rocket.svg", "../assets/images/project-rail.svg", "../assets/images/project-aux.svg"],
    },
    {
      id: "zephyr-r2",
      name: "Zephyr R2",
      family: "cohetes",
      year: 2024,
      status: "Completed",
      summary: "Vehiculo de madurez tecnica que consolido avionica embarcada y procesos de integracion rapida.",
      description:
        "Proyecto de referencia para el salto de capacidad entre 2024 y 2025. Permitio validar protocolos de ensamblaje y ensayos de vuelo instrumentado.",
      image: "../assets/images/project-rocket.svg",
      highlight: "Base tecnica del roadmap actual.",
      specs: [
        { label: "Altura", value: "2.72 m" },
        { label: "Masa al despegue", value: "16.1 kg" },
        { label: "Altitud alcanzada", value: "3.9 km AGL" },
        { label: "Campana", value: "Spring 2024" },
      ],
      related: ["helix-m2", "apex-rail-l"],
      gallery: ["../assets/images/project-rocket.svg", "../assets/images/project-motor.svg"],
    },
    {
      id: "atlas-rx",
      name: "Atlas RX Concept",
      family: "cohetes",
      year: 2026,
      status: "Concept",
      summary: "Concepto de siguiente generacion para mayor altitud y capacidad de carga util universitaria.",
      description:
        "Linea conceptual para explorar nuevas configuraciones de fuselaje y avionica modular escalable.",
      image: "../assets/images/project-rocket.svg",
      highlight: "Exploracion de arquitectura futura.",
      specs: [
        { label: "Madurez", value: "Preliminary design" },
        { label: "Objetivo", value: "Escalado de plataforma" },
        { label: "Fase", value: "Roadmap" },
      ],
      related: ["telemetry-core"],
      gallery: ["../assets/images/project-rocket.svg", "../assets/images/project-aux.svg"],
    },
    {
      id: "ignis-m1",
      name: "Ignis M1",
      family: "motores",
      year: 2025,
      status: "Hot-fire testing",
      summary: "Motor solido de media potencia para plataformas R-series con foco en repetibilidad de empuje.",
      description:
        "Incluye desarrollo de geometria de grano, validacion termica y sensorizacion de banco de alta frecuencia.",
      image: "../assets/images/project-motor.svg",
      highlight: "Programa motor principal de la temporada.",
      specs: [
        { label: "Impulso total", value: "7.6 kN.s" },
        { label: "Empuje pico", value: "5.1 kN" },
        { label: "Tiempo de combustion", value: "2.6 s" },
      ],
      related: ["skylance-r1", "thrust-bench"],
      gallery: ["../assets/images/project-motor.svg", "../assets/images/project-aux.svg"],
    },
    {
      id: "helix-m2",
      name: "Helix M2",
      family: "motores",
      year: 2024,
      status: "Validated",
      summary: "Motor de validacion que permitio cerrar metodologias de ensayo y analisis de rendimiento.",
      description:
        "Fue el primer programa con trazabilidad completa de parametros termicos y curva de empuje post-procesada.",
      image: "../assets/images/project-motor.svg",
      highlight: "Motor base para evolucion M1.",
      specs: [
        { label: "Impulso total", value: "5.9 kN.s" },
        { label: "Empuje medio", value: "3.4 kN" },
        { label: "Ciclos de test", value: "9" },
      ],
      related: ["zephyr-r2"],
      gallery: ["../assets/images/project-motor.svg", "../assets/images/project-rocket.svg"],
    },
    {
      id: "vector-rail-x",
      name: "Vector Rail X",
      family: "launch-rails",
      year: 2025,
      status: "Operational",
      summary: "Sistema de lanzamiento modular para campanas multi-vehiculo con ajuste fino de guiado.",
      description:
        "Combina rigidez estructural, facilidad de montaje y sensorizacion de estado para operaciones de campo.",
      image: "../assets/images/project-rail.svg",
      highlight: "Rail principal de operaciones 2025.",
      specs: [
        { label: "Longitud util", value: "6.2 m" },
        { label: "Ajuste angular", value: "0-12 deg" },
        { label: "Tiempo de montaje", value: "28 min" },
      ],
      related: ["skylance-r1"],
      gallery: ["../assets/images/project-rail.svg", "../assets/images/project-rocket.svg"],
    },
    {
      id: "apex-rail-l",
      name: "Apex Rail L",
      family: "launch-rails",
      year: 2023,
      status: "Legacy",
      summary: "Plataforma de lanzamiento de primera generacion usada en campanas iniciales.",
      description:
        "Proyecto historico que consolido criterios de seguridad operativa y base mecanica para sistemas actuales.",
      image: "../assets/images/project-rail.svg",
      highlight: "Pieza clave en la evolucion del equipo.",
      specs: [
        { label: "Longitud util", value: "4.8 m" },
        { label: "Campanas", value: "2023" },
        { label: "Estado", value: "Uso interno de pruebas" },
      ],
      related: ["zephyr-r2"],
      gallery: ["../assets/images/project-rail.svg"],
    },
    {
      id: "telemetry-core",
      name: "Telemetry Core",
      family: "auxiliary",
      year: 2025,
      status: "Active",
      summary: "Pipeline de telemetria y observabilidad para misiones de vuelo y ensayos de banco.",
      description:
        "Proyecto transversal para capturar, visualizar y versionar datos tecnicos en todas las familias de desarrollo.",
      image: "../assets/images/project-aux.svg",
      highlight: "Columna vertebral de datos tecnicos.",
      specs: [
        { label: "Frecuencia", value: "200 Hz" },
        { label: "Canales", value: "64" },
        { label: "Sincronizacion", value: "Timestamped" },
      ],
      related: ["adrian-soto", "amaia-lorenzo"],
      gallery: ["../assets/images/project-aux.svg", "../assets/images/project-motor.svg"],
    },
    {
      id: "recovery-suite",
      name: "Recovery Suite",
      family: "auxiliary",
      year: 2024,
      status: "Iterative",
      summary: "Conjunto de herramientas de validacion para secuencias de recuperacion y despliegue.",
      description:
        "Incluye banco de eyeccion, simulacion de eventos y checklist operacional para test de recuperacion.",
      image: "../assets/images/project-aux.svg",
      highlight: "Sistema auxiliar de seguridad de vuelo.",
      specs: [
        { label: "Escenarios", value: "12 configuraciones" },
        { label: "Ensayos", value: "45+" },
        { label: "Uso", value: "Pre-flight" },
      ],
      related: ["skylance-r1", "gorka-lafuente"],
      gallery: ["../assets/images/project-aux.svg"],
    },
    {
      id: "thrust-bench",
      name: "Thrust Bench 2.0",
      family: "auxiliary",
      year: 2025,
      status: "Commissioning",
      summary: "Banco de ensayos para propulsion con adquisicion de alta precision y control remoto.",
      description:
        "Permite repetir campanas de pruebas bajo mismas condiciones y comparar iteraciones de motor.",
      image: "../assets/images/project-aux.svg",
      highlight: "Infraestructura critica de propulsion.",
      specs: [
        { label: "Carga maxima", value: "18 kN" },
        { label: "Resolucion", value: "0.2% FS" },
        { label: "Control", value: "Remote safe zone" },
      ],
      related: ["ignis-m1"],
      gallery: ["../assets/images/project-aux.svg", "../assets/images/project-motor.svg"],
    },
  ];

  const SPONSORS = [
    {
      id: "orbital-dynamics",
      name: "Orbital Dynamics Lab",
      tier: "Cosmos",
      sector: "Aerospace R&D",
      summary: "Soporte en materiales avanzados y ensayos estructurales.",
      detail: "Colabora en revisiones de diseno y facilita acceso a equipamiento de validacion mecanica.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "vector-industries",
      name: "Vector Industries",
      tier: "Cosmos",
      sector: "Advanced Manufacturing",
      summary: "Fabricacion de componentes de precision para fuselaje y rail.",
      detail: "Aporta soporte en mecanizado de piezas criticas y asesoramiento de tolerancias.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "nova-composites",
      name: "Nova Composites",
      tier: "Galaxy",
      sector: "Composites",
      summary: "Proveedores de materiales compuestos para estructuras ligeras.",
      detail: "Suministra prepregs y soporte tecnico para procesos de laminado.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "altair-tools",
      name: "Altair Tools",
      tier: "Galaxy",
      sector: "Industrial Tooling",
      summary: "Herramienta tecnica para manufactura y montaje.",
      detail: "Facilita herramientas de banco y utilajes para integracion de subsistemas.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "aeroforge",
      name: "AeroForge",
      tier: "Nebula",
      sector: "Mechanical Engineering",
      summary: "Colaboracion en diseno mecanico y revisiones de integridad.",
      detail: "Participa en sesiones tecnicas de revision de interfaces estructurales.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "stellar-electronics",
      name: "Stellar Electronics",
      tier: "Star",
      sector: "Embedded Systems",
      summary: "Componentes para avionica y sensorizacion.",
      detail: "Aporta placas, conectores y soporte de integracion electronica.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "zenith-rail",
      name: "Zenith Rail Systems",
      tier: "Satellite",
      sector: "Launch Infrastructure",
      summary: "Soporte para arquitectura de launch rails.",
      detail: "Contribuye con perfiles tecnicos y asesoramiento en sistemas de guiado.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "campus-foundation",
      name: "Campus Engineering Foundation",
      tier: "Earth",
      sector: "Education",
      summary: "Apoyo institucional y logistica universitaria.",
      detail: "Respaldo operativo para espacios de trabajo y actividades academicas.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "cloudtrack",
      name: "CloudTrack",
      tier: "Software",
      sector: "Data Platform",
      summary: "Herramientas de datos y observabilidad tecnica.",
      detail: "Permite gestionar tableros de datos para seguimiento de rendimiento y ensayos.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
    {
      id: "simuworks",
      name: "SimuWorks",
      tier: "Software",
      sector: "Simulation",
      summary: "Licencias de simulacion para validacion de diseno.",
      detail: "Facilita entorno de simulacion para estudios preliminares de vuelo y propulsion.",
      logo: "../assets/images/sponsor-placeholder.svg",
      website: "https://example.com",
    },
  ];

  window.BISKY_DATA = {
    teamInfo: TEAM_INFO,
    years: YEARS,
    departmentOrder: DEPARTMENT_ORDER,
    positionOrder: POSITION_ORDER,
    members: MEMBERS,
    projectFamilies: PROJECT_FAMILIES,
    projects: PROJECTS,
    sponsors: SPONSORS,
  };
})();
